# Support Vector Machine

![http://docs.opencv.org/_images/optimal-hyperplane.png](http://docs.opencv.org/_images/optimal-hyperplane.png)



They are an evolved form of the Perceptron.

See this link:  http://www.tristanfletcher.co.uk/SVM%20Explained.pdf  for a nice paper (first 10 pages) that goes into the math.  Also here for the scikit-learn page:  http://scikit-learn.org/stable/modules/svm.html#kernel-functions




In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import Perceptron
from sklearn.svm import SVC
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('mystery.csv',header=None)
mdata = df[[0,1]].values
cats = df[2].values

Xtrain, Xtest, Ctrain, Ctest = train_test_split(mdata, cats)

In [3]:
classifier = SVC()
classifier.fit(Xtrain,Ctrain)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [4]:
Cpred = classifier.predict(Xtest)
print(classification_report(Ctest,Cpred))

             precision    recall  f1-score   support

         -1       1.00      0.96      0.98        24
          1       0.96      1.00      0.98        26

avg / total       0.98      0.98      0.98        50



## Compare the performance of the Perceptron and the SVM on the iris and digits data

In [26]:
from sklearn import datasets

iris = datasets.load_iris()
digits = datasets.load_digits()

ix, iy = iris.data, iris.target
dx, dy = digits.data, digits.target

ixtrain, ixtest, iytrain, iytest = train_test_split(ix, iy)
dxtrain, dxtest, dytrain, dytest = train_test_split(dx, dy)

thinker1 = Perceptron(n_iter=10000)
thinker2 = Perceptron(n_iter=10000)

thinker1.fit(ixtrain, iytrain)
thinker2.fit(dxtrain, dytrain)

betterthinker1 = SVC(kernel='poly')
betterthinker2 = SVC(kernel='poly')

betterthinker1.fit(ixtrain, iytrain)
betterthinker2.fit(dxtrain, dytrain)

result1 = thinker1.predict(ixtest)
result2 = thinker2.predict(dxtest)
result3 = betterthinker1.predict(ixtest)
result4 = betterthinker2.predict(dxtest)

print("Iris with perceptron\n")
print(classification_report(iytest, result1, target_names = iris.target_names))
print(confusion_matrix(iytest, result1))
print("Digits with perceptron\n")
print(classification_report(dytest, result2))
print(confusion_matrix(dytest, result2))
print("Iris with SVM\n")
print(classification_report(iytest, result3, target_names = iris.target_names))
print(confusion_matrix(iytest, result3))
print("Digits with SVM\n")
print(classification_report(dytest, result4))
print(confusion_matrix(dytest, result4))

Iris with perceptron

             precision    recall  f1-score   support

     setosa       0.52      0.92      0.67        13
 versicolor       0.80      0.31      0.44        13
  virginica       1.00      0.83      0.91        12

avg / total       0.77      0.68      0.67        38

[[12  1  0]
 [ 9  4  0]
 [ 2  0 10]]
Digits with perceptron

             precision    recall  f1-score   support

          0       0.98      1.00      0.99        42
          1       0.95      0.85      0.90        62
          2       0.92      1.00      0.96        35
          3       0.94      0.96      0.95        48
          4       0.95      0.98      0.96        42
          5       0.98      0.91      0.94        46
          6       0.89      1.00      0.94        42
          7       0.98      0.98      0.98        42
          8       0.90      0.88      0.89        41
          9       0.96      0.94      0.95        50

avg / total       0.95      0.94      0.94       450

[[42  0  0